print("##################################")
print("            PyFinance             ")
print("##################################")
print("[1] Login")
print("[2] Registro")
print("[4] Listar Repúblicas")
print("[5] Pesquisar por Repúblicas")
print("[0] Sair do Programa")
print("##################################")
option = int(input("Resposta: "))
